export const transitionStatuses = {
  REQUEST: 'transition/request',
  ENQUIRE: 'transition/enquire',
  CONFIRM: 'transition/confirm-payment',
  AFTER_ENQUIRE: 'transition/request-payment-after-enquiry',
  ACCEPT: 'transition/accept',
  DECLINE: 'transition/decline',
  EXPIRED: 'transition/expired',
  COMPLETE: 'transition/complete',
  DELIVERED: 'transition/expire-provider-review-period',
  REVIEW_CUSTOMER_1: 'transition/review-1-by-customer',
  REVIEW_CUSTOMER_2: 'transition/review-2-by-customer',
  REVIEW_PROVIDER_1: 'transition/review-1-by-provider',
  REVIEW_PROVIDER_2: 'transition/review-2-by-provider',
};
